### ISSUE TITLE
PollCard warning on client build

### ISSUE THREAD

**Issue by filg68** [hatchways/team-evergreen#188]
./src/components/PollCard.js
  Line 40:  React Hook React.useEffect has a missing dependency: 'props'. Either include it or remove the dependency array. However, 'props' will change when *any* prop changes, so the preferred fix is to destructure the 'props' object outside of the useEffect call and refer to those specific props inside React.useEffect  react-hooks/exhaustive-deps

**Comment by IoPhoenix** [comment]
I'm aware of this issue, it's weird that if I do as the warning suggests (destructure props) it doesn't help. If I pass props as a dependency, all polls are remounted when a new poll is created which is not efficient. I will look into this.
